### ISSUE TITLE
Admin site fail to start

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/laobian#41]
```
May 01 08:25:21 laobian admin.laobian.me[13761]: warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
May 01 08:25:21 laobian admin.laobian.me[13761]:       No XML encryptor configured. Key {64be033b-515d-4292-acde-e90ba5781818} may be persisted to storage in unencrypted form.
May 01 08:25:24 laobian admin.laobian.me[13761]: Hosting environment: Production
May 01 08:25:24 laobian admin.laobian.me[13761]: Content root path: /var/www/laobian/admin
May 01 08:25:24 laobian admin.laobian.me[13761]: Now listening on: http://localhost:8001
May 01 08:25:24 laobian admin.laobian.me[13761]: Application started. Press Ctrl+C to shut down.
May 01 08:27:23 laobian admin.laobian.me[13761]: fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
May 01 08:27:23 laobian admin.laobian.me[13761]:       An exception was thrown while deserializing the token.
May 01 08:27:23 laobian admin.laobian.me[13761]: System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.Cryptographic
May 01 08:27:23 laobian admin.laobian.me[13761]:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean a
May 01 08:27:23 laobian admin.laobian.me[13761]:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Bool
May 01 08:27:23 laobian admin.laobian.me[13761]:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
May 01 08:27:23 laobian admin.laobian.me[13761]:    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
May 01 08:27:23 laobian admin.laobian.me[13761]:    --- End of inner exception stack trace ---
May 01 08:27:23 laobian admin.laobian.me[13761]:    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
May 01 08:27:23 laobian admin.laobian.me[13761]:    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
May 01 08:46:09 laobian systemd[1]: Stopping https://admin.laobian.me...
May 01 08:46:09 laobian admin.laobian.me[13761]: Application is shutting down...
```

**Comment by JerryBian** [comment]
https://github.com/aspnet/DataProtection/blob/rel/1.1.0/samples/AzureBlob/Program.cs

https://github.com/aspnet/Antiforgery/issues/173
